language: node_js
node_js:
  - "6.2"

sudo: required
services:
  - docker

install:
  - docker build -t gtrias/plugged-nginx .
  - npm install

script:
  - docker run -d --name plugged-nginx gtrias/plugged-nginx
  - docker ps | grep -q  plugged-nginx

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push gtrias/plugged-nginx;
    fi
